FROM python:3.8.10

WORKDIR /tmp
RUN apt-get update
RUN apt-get install -y gcc
RUN apt-get install -y build-essential
RUN apt-get install -y python3-dev
ENV VIRTUAL_ENV=/tmp/venv
RUN python3 -m venv $VIRTUAL_ENV
# https://pythonspeed.com/articles/activate-virtualenv-dockerfile/
ENV PATH="$VIRTUAL_ENV/bin:$PATH"


# Install dependencies:
COPY requirements.txt .
RUN pip install -r requirements.txt

# Kotti config.
COPY app.ini .

# Command to be executed when image runs.
CMD [ "pserve", "-v", "app.ini" ]
